### ISSUE TITLE
The key function of this plugin

### ISSUE THREAD

**Issue by lobbia** [haydenull/logseq-plugin-git#27]
A dumb question, how is the plugin built, and what's the key features. I was not able to find out here or from google. As logseq desktop version does have git build-in already and i can run git command from popup box so feel confused. Is this plugin adds some workflow like auto check/push, land GUI shortcut to git command, or it also deploys another git from scratch?
a more question, can it add auto pull after logseq startup, but not just checking/reminding the difference with remote?

**Comment by haydenull** [comment]
I'm sorry I keep forgetting to add instructions for use

I wrote this plugin to address the following issues.
1. knowing explicitly if there are unsaved notes in the current repository and if they are synchronized with the remote repository.
    - When there are unsaved files locally, the plugin will show a red indicator in the toolbar icon
2. Quickly commit changes to notes.
  - The plugin provides shortcut keys (mod+s) to perform commit&push operations
3. provide buttons to quickly execute common commands
  - Click the plugin icon, and the drop-down menu will show you some buttons to help you quickly execute commands (you can specify the desired buttons in the settings)
4. prompt me if I have synchronized with the remote repository
  - I use a mac at work and windows at home. sometimes I commit actions on the mac to github later. I forget to pull code before writing notes on windows at home, which leads to frequent note conflicts. The plugin automatically detects if the current repository is up-to-date and prompts when logseq starts and other times.

I disabled auto commit on logseq because I didn't want to have too many commits in my repository, which caused the problem that I had to manage the repository manually, and this plugin is designed to make it easier for me to use git to store notes.

Also, there is an app for mac called shortery that automates shortcut execution, and with it you can push or pull code when the mac is locked or unlocked.

This is just my own way of using the plugin, you can use it any way you like, or use logseq's own git feature

**Comment by lobbia** [comment]
great! cristical clear and thanks for sharing your experiences! this plugin made my logseq sync almost perfect. Maybe you can consider sharing this with more people in in README. 

 BTW, can you provide one more shortcut key option for 'Pull“? Sorry if I ask too much ;)

**Comment by haydenull** [comment]
1. I apologize for the inconvenience, it seems that I accidentally closed the result message of the pull command. In the meantime, you can use "pull rebase" instead. I will make sure to fix this issue in the next release.

2. I have the plan to enable users to configure all of the short keys for commands. This will make the user experience more customizable and convenient.

3. The popup that you are seeing is a feature of Logseq. Unfortunately, I do not think that there are any good methods for addressing this issue at this time.

**Comment by lobbia** [comment]
Thank you!! Really love logseq and your plugin!
